// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: cosmos/epochs/v1beta1/events.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "cosmos.epochs.v1beta1";
function createBaseEventEpochEnd() {
    return { epochNumber: 0 };
}
export const EventEpochEnd = {
    encode(message, writer = new BinaryWriter()) {
        if (message.epochNumber !== 0) {
            writer.uint32(8).int64(message.epochNumber);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseEventEpochEnd();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 8) {
                            break;
                        }
                        message.epochNumber = longToNumber(reader.int64());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            epochNumber: isSet(object.epochNumber)
                ? globalThis.Number(object.epochNumber)
                : isSet(object.epoch_number)
                    ? globalThis.Number(object.epoch_number)
                    : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.epochNumber !== 0) {
            obj.epochNumber = Math.round(message.epochNumber);
        }
        return obj;
    },
    create(base) {
        return EventEpochEnd.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventEpochEnd();
        message.epochNumber = object.epochNumber ?? 0;
        return message;
    },
};
function createBaseEventEpochStart() {
    return { epochNumber: 0, epochStartTime: 0 };
}
export const EventEpochStart = {
    encode(message, writer = new BinaryWriter()) {
        if (message.epochNumber !== 0) {
            writer.uint32(8).int64(message.epochNumber);
        }
        if (message.epochStartTime !== 0) {
            writer.uint32(16).int64(message.epochStartTime);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseEventEpochStart();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 8) {
                            break;
                        }
                        message.epochNumber = longToNumber(reader.int64());
                        continue;
                    }
                    case 2: {
                        if (tag !== 16) {
                            break;
                        }
                        message.epochStartTime = longToNumber(reader.int64());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            epochNumber: isSet(object.epochNumber)
                ? globalThis.Number(object.epochNumber)
                : isSet(object.epoch_number)
                    ? globalThis.Number(object.epoch_number)
                    : 0,
            epochStartTime: isSet(object.epochStartTime)
                ? globalThis.Number(object.epochStartTime)
                : isSet(object.epoch_start_time)
                    ? globalThis.Number(object.epoch_start_time)
                    : 0,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.epochNumber !== 0) {
            obj.epochNumber = Math.round(message.epochNumber);
        }
        if (message.epochStartTime !== 0) {
            obj.epochStartTime = Math.round(message.epochStartTime);
        }
        return obj;
    },
    create(base) {
        return EventEpochStart.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseEventEpochStart();
        message.epochNumber = object.epochNumber ?? 0;
        message.epochStartTime = object.epochStartTime ?? 0;
        return message;
    },
};
function longToNumber(int64) {
    const num = globalThis.Number(int64.toString());
    if (num > globalThis.Number.MAX_SAFE_INTEGER) {
        throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
    }
    if (num < globalThis.Number.MIN_SAFE_INTEGER) {
        throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
    }
    return num;
}
function isSet(value) {
    return value !== null && value !== undefined;
}
