// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: ibc/applications/transfer/v1/denomtrace.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
export const protobufPackage = "ibc.applications.transfer.v1";
function createBaseDenomTrace() {
    return { path: "", baseDenom: "" };
}
export const DenomTrace = {
    encode(message, writer = new BinaryWriter()) {
        if (message.path !== "") {
            writer.uint32(10).string(message.path);
        }
        if (message.baseDenom !== "") {
            writer.uint32(18).string(message.baseDenom);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseDenomTrace();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.path = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.baseDenom = reader.string();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            path: isSet(object.path) ? globalThis.String(object.path) : "",
            baseDenom: isSet(object.baseDenom)
                ? globalThis.String(object.baseDenom)
                : isSet(object.base_denom)
                    ? globalThis.String(object.base_denom)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.path !== "") {
            obj.path = message.path;
        }
        if (message.baseDenom !== "") {
            obj.baseDenom = message.baseDenom;
        }
        return obj;
    },
    create(base) {
        return DenomTrace.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseDenomTrace();
        message.path = object.path ?? "";
        message.baseDenom = object.baseDenom ?? "";
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
