// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: ibc/applications/transfer/v1/genesis.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Coin } from "../../../../cosmos/base/v1beta1/coin";
import { Denom } from "./token";
import { Params } from "./transfer";
export const protobufPackage = "ibc.applications.transfer.v1";
function createBaseGenesisState() {
    return { portId: "", denoms: [], params: undefined, totalEscrowed: [] };
}
export const GenesisState = {
    encode(message, writer = new BinaryWriter()) {
        if (message.portId !== "") {
            writer.uint32(10).string(message.portId);
        }
        for (const v of message.denoms) {
            Denom.encode(v, writer.uint32(18).fork()).join();
        }
        if (message.params !== undefined) {
            Params.encode(message.params, writer.uint32(26).fork()).join();
        }
        for (const v of message.totalEscrowed) {
            Coin.encode(v, writer.uint32(34).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseGenesisState();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.portId = reader.string();
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.denoms.push(Denom.decode(reader, reader.uint32()));
                        continue;
                    }
                    case 3: {
                        if (tag !== 26) {
                            break;
                        }
                        message.params = Params.decode(reader, reader.uint32());
                        continue;
                    }
                    case 4: {
                        if (tag !== 34) {
                            break;
                        }
                        message.totalEscrowed.push(Coin.decode(reader, reader.uint32()));
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            portId: isSet(object.portId)
                ? globalThis.String(object.portId)
                : isSet(object.port_id)
                    ? globalThis.String(object.port_id)
                    : "",
            denoms: globalThis.Array.isArray(object?.denoms) ? object.denoms.map((e) => Denom.fromJSON(e)) : [],
            params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
            totalEscrowed: globalThis.Array.isArray(object?.totalEscrowed)
                ? object.totalEscrowed.map((e) => Coin.fromJSON(e))
                : globalThis.Array.isArray(object?.total_escrowed)
                    ? object.total_escrowed.map((e) => Coin.fromJSON(e))
                    : [],
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.portId !== "") {
            obj.portId = message.portId;
        }
        if (message.denoms?.length) {
            obj.denoms = message.denoms.map((e) => Denom.toJSON(e));
        }
        if (message.params !== undefined) {
            obj.params = Params.toJSON(message.params);
        }
        if (message.totalEscrowed?.length) {
            obj.totalEscrowed = message.totalEscrowed.map((e) => Coin.toJSON(e));
        }
        return obj;
    },
    create(base) {
        return GenesisState.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseGenesisState();
        message.portId = object.portId ?? "";
        message.denoms = object.denoms?.map((e) => Denom.fromPartial(e)) || [];
        message.params = (object.params !== undefined && object.params !== null)
            ? Params.fromPartial(object.params)
            : undefined;
        message.totalEscrowed = object.totalEscrowed?.map((e) => Coin.fromPartial(e)) || [];
        return message;
    },
};
function isSet(value) {
    return value !== null && value !== undefined;
}
