import { computed, ref } from "vue";

export type Locale = "en" | "ru" | "uk";

const messages = {
  en: {
    portfolio: "Portfolio",
    data: "Data",
    assets: "Assets",
    transactions: "Transactions",
    noAssets: "You have no assets",
    transactionEmpty: "Transaction history is empty",
    send: "Send",
    receive: "Receive",
    sendTo: "Send to",
    recipientAddress: "Recipient address",
    advanced: "Advanced",
    estimatedFee: "Estimated fee",
    success: "Tx submitted successfully",
    networkData: "Network data",
    tokenomics: "Tokenomics",
    validatorReserve: "Validator reserve",
    restrictedAccounts: "Restricted accounts",
    validatorCommissions: "Validator commissions",
    searchAssets: "Search assets",
    connectedWallet: "Connected wallet",
    localWallets: "Local wallets",
    importWallet: "Import another wallet",
    disconnectWallet: "Disconnect wallet",
    settings: "Settings",
    asset: "Asset",
    availableBalance: "Available balance",
    noResultsFor: "No results for",
    tryAnotherSearch: "Try again with another search",
    showMore: "Show more",
    liveTokenomics: "Live tokenomics and allocation state from the Ferac chain.",
    denom: "Denom",
    maxSupply: "Max supply",
    networkFee: "Network fee",
    validatorShare: "Validator share",
    genesisValidators: "Genesis validators",
    finalityThreshold: "Finality threshold",
    remaining: "Remaining",
    nextRelease: "Next release",
    epoch: "Epoch",
    lastEpoch: "Last epoch",
    address: "Address",
    category: "Category",
    released: "Released",
    validator: "Validator",
    operatorAddress: "Operator address",
    commission: "Commission",
    outstandingRewards: "Outstanding rewards",
    totalVisibleRewards: "Total visible rewards",
    noRestrictedAccounts: "No restricted accounts",
    noValidatorCommissions: "No validator commissions",
    allRightsReserved: "All rights reserved.",
    txSuccess: "Success",
    txFailed: "Failed",
    fees: "Fees",
    addAsset: "Add asset",
    selectAsset: "Select asset",
    reference: "Reference (memo)",
    channel: "Channel",
    enterReference: "Enter a reference",
    enterChannel: "Enter a channel",
    available: "available",
    from: "from",
    to: "to"
  },
  ru: {
    portfolio: "Портфель",
    data: "Данные",
    assets: "Активы",
    transactions: "Транзакции",
    noAssets: "У вас нет активов",
    transactionEmpty: "История транзакций пуста",
    send: "Отправить",
    receive: "Получить",
    sendTo: "Отправить на",
    recipientAddress: "Адрес получателя",
    advanced: "Дополнительно",
    estimatedFee: "Расчётная комиссия",
    success: "Транзакция отправлена",
    networkData: "Данные сети",
    tokenomics: "Токеномика",
    validatorReserve: "Резерв валидаторов",
    restrictedAccounts: "Ограниченные аккаунты",
    validatorCommissions: "Комиссии валидаторов",
    searchAssets: "Поиск активов",
    connectedWallet: "Подключённый кошелёк",
    localWallets: "Локальные кошельки",
    importWallet: "Импортировать другой кошелёк",
    disconnectWallet: "Отключить кошелёк",
    settings: "Настройки",
    asset: "Актив",
    availableBalance: "Доступный баланс",
    noResultsFor: "Нет результатов для",
    tryAnotherSearch: "Попробуйте другой запрос",
    showMore: "Показать ещё",
    liveTokenomics: "Актуальное состояние токеномики и распределения в сети Ferac.",
    denom: "Деном",
    maxSupply: "Максимальная эмиссия",
    networkFee: "Комиссия сети",
    validatorShare: "Доля валидаторов",
    genesisValidators: "Валидаторы генезиса",
    finalityThreshold: "Порог финальности",
    remaining: "Остаток",
    nextRelease: "Следующее высвобождение",
    epoch: "Эпоха",
    lastEpoch: "Последняя эпоха",
    address: "Адрес",
    category: "Категория",
    released: "Высвобождено",
    validator: "Валидатор",
    operatorAddress: "Адрес оператора",
    commission: "Комиссия",
    outstandingRewards: "Невыплаченные награды",
    totalVisibleRewards: "Всего видимых наград",
    noRestrictedAccounts: "Нет ограниченных аккаунтов",
    noValidatorCommissions: "Нет комиссий валидаторов",
    allRightsReserved: "Все права защищены.",
    txSuccess: "Успешно",
    txFailed: "Ошибка",
    fees: "Комиссии",
    addAsset: "Добавить актив",
    selectAsset: "Выбрать актив",
    reference: "Ссылка (мемо)",
    channel: "Канал",
    enterReference: "Введите ссылку",
    enterChannel: "Введите канал",
    available: "доступно",
    from: "от",
    to: "кому",
  },
  uk: {
    portfolio: "Портфель",
    data: "Дані",
    assets: "Активи",
    transactions: "Транзакції",
    noAssets: "У вас немає активів",
    transactionEmpty: "Історія транзакцій порожня",
    send: "Надіслати",
    receive: "Отримати",
    sendTo: "Надіслати на",
    recipientAddress: "Адреса отримувача",
    advanced: "Додатково",
    estimatedFee: "Розрахункова комісія",
    success: "Транзакцію надіслано",
    networkData: "Дані мережі",
    tokenomics: "Токеноміка",
    validatorReserve: "Резерв валідаторів",
    restrictedAccounts: "Обмежені акаунти",
    validatorCommissions: "Комісії валідаторів",
    searchAssets: "Пошук активів",
    connectedWallet: "Підключений гаманець",
    localWallets: "Локальні гаманці",
    importWallet: "Імпортувати інший гаманець",
    disconnectWallet: "Відключити гаманець",
    settings: "Налаштування",
    asset: "Актив",
    availableBalance: "Доступний баланс",
    noResultsFor: "Немає результатів для",
    tryAnotherSearch: "Спробуйте інший запит",
    showMore: "Показати ще",
    liveTokenomics: "Актуальний стан токеноміки та розподілу в мережі Ferac.",
    denom: "Деном",
    maxSupply: "Максимальна емісія",
    networkFee: "Комісія мережі",
    validatorShare: "Частка валідаторів",
    genesisValidators: "Валідатори генезису",
    finalityThreshold: "Поріг фінальності",
    remaining: "Залишок",
    nextRelease: "Наступне вивільнення",
    epoch: "Епоха",
    lastEpoch: "Остання епоха",
    address: "Адреса",
    category: "Категорія",
    released: "Вивільнено",
    validator: "Валідатор",
    operatorAddress: "Адреса оператора",
    commission: "Комісія",
    outstandingRewards: "Невиплачені винагороди",
    totalVisibleRewards: "Усього видимих винагород",
    noRestrictedAccounts: "Немає обмежених акаунтів",
    noValidatorCommissions: "Немає комісій валідаторів",
    allRightsReserved: "Усі права захищено.",
    txSuccess: "Успішно",
    txFailed: "Помилка",
    fees: "Комісії",
    addAsset: "Додати актив",
    selectAsset: "Вибрати актив",
    reference: "Посилання (мемо)",
    channel: "Канал",
    enterReference: "Введіть посилання",
    enterChannel: "Введіть канал",
    available: "доступно",
    from: "від",
    to: "кому",
  },
} as const;

type MessageKey = keyof typeof messages.en;

const locale = ref<Locale>(
  (localStorage.getItem("ferac.locale") as Locale) || "en"
);

export const useLanguage = () => {
  const setLocale = (nextLocale: Locale) => {
    locale.value = nextLocale;
    localStorage.setItem("ferac.locale", nextLocale);
  };

  const t = (key: MessageKey) => computed(() => messages[locale.value][key]);

  return { locale, setLocale, t };
};
