// Generated by Ignite ignite.com/cli
import { SigningStargateClient } from "@cosmjs/stargate";
import { Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { Api } from "./rest";
import { MsgAuthorizeCircuitBreaker } from "./types/cosmos/circuit/v1/tx";
import { MsgTripCircuitBreaker } from "./types/cosmos/circuit/v1/tx";
import { MsgResetCircuitBreaker } from "./types/cosmos/circuit/v1/tx";
import { Permissions as typePermissions } from "./types";
import { GenesisAccountPermissions as typeGenesisAccountPermissions } from "./types";
export { MsgAuthorizeCircuitBreaker, MsgTripCircuitBreaker, MsgResetCircuitBreaker };
export const registry = new Registry(msgTypes);
function getStructure(template) {
    const structure = { fields: [] };
    for (let [key, value] of Object.entries(template)) {
        let field = { name: key, type: typeof value };
        structure.fields.push(field);
    }
    return structure;
}
const defaultFee = {
    amount: [],
    gas: "200000",
};
export const txClient = ({ signer, prefix, addr } = { addr: "http://localhost:26657", prefix: "cosmos" }) => {
    return {
        async sendMsgAuthorizeCircuitBreaker({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgAuthorizeCircuitBreaker: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgAuthorizeCircuitBreaker({ value: MsgAuthorizeCircuitBreaker.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgAuthorizeCircuitBreaker: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgTripCircuitBreaker({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgTripCircuitBreaker: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgTripCircuitBreaker({ value: MsgTripCircuitBreaker.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgTripCircuitBreaker: Could not broadcast Tx: ' + e.message);
            }
        },
        async sendMsgResetCircuitBreaker({ value, fee, memo }) {
            if (!signer) {
                throw new Error('TxClient:sendMsgResetCircuitBreaker: Unable to sign Tx. Signer is not present.');
            }
            try {
                const { address } = (await signer.getAccounts())[0];
                const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry });
                let msg = this.msgResetCircuitBreaker({ value: MsgResetCircuitBreaker.fromPartial(value) });
                return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo);
            }
            catch (e) {
                throw new Error('TxClient:sendMsgResetCircuitBreaker: Could not broadcast Tx: ' + e.message);
            }
        },
        msgAuthorizeCircuitBreaker({ value }) {
            try {
                return { typeUrl: "/cosmos.circuit.v1.MsgAuthorizeCircuitBreaker", value: MsgAuthorizeCircuitBreaker.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgAuthorizeCircuitBreaker: Could not create message: ' + e.message);
            }
        },
        msgTripCircuitBreaker({ value }) {
            try {
                return { typeUrl: "/cosmos.circuit.v1.MsgTripCircuitBreaker", value: MsgTripCircuitBreaker.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgTripCircuitBreaker: Could not create message: ' + e.message);
            }
        },
        msgResetCircuitBreaker({ value }) {
            try {
                return { typeUrl: "/cosmos.circuit.v1.MsgResetCircuitBreaker", value: MsgResetCircuitBreaker.fromPartial(value) };
            }
            catch (e) {
                throw new Error('TxClient:MsgResetCircuitBreaker: Could not create message: ' + e.message);
            }
        },
    };
};
export const queryClient = ({ addr: addr } = { addr: "http://localhost:1317" }) => {
    return new Api({ baseURL: addr });
};
class SDKModule {
    constructor(client) {
        this.registry = [];
        this.query = queryClient({ addr: client.env.apiURL });
        this.updateTX(client);
        this.structure = {
            Permissions: getStructure(typePermissions.fromPartial({})),
            GenesisAccountPermissions: getStructure(typeGenesisAccountPermissions.fromPartial({})),
        };
        client.on('signer-changed', (signer) => {
            this.updateTX(client);
        });
    }
    updateTX(client) {
        const methods = txClient({
            signer: client.signer,
            addr: client.env.rpcURL,
            prefix: client.env.prefix ?? "cosmos",
        });
        this.tx = methods;
        for (let m in methods) {
            this.tx[m] = methods[m].bind(this.tx);
        }
    }
}
;
const IgntModule = (test) => {
    return {
        module: {
            CosmosCircuitV_1: new SDKModule(test)
        },
        registry: msgTypes
    };
};
export default IgntModule;
