// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: ferac/ferac/v1/query.proto
/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { PageRequest, PageResponse } from "../../../cosmos/base/query/v1beta1/pagination";
import { Params } from "./params";
import { RestrictedAccount, ValidatorPerformance, ValidatorReserve } from "./tokenomics";
export const protobufPackage = "ferac.ferac.v1";
function createBaseQueryParamsRequest() {
    return {};
}
export const QueryParamsRequest = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryParamsRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return QueryParamsRequest.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseQueryParamsRequest();
        return message;
    },
};
function createBaseQueryParamsResponse() {
    return { params: undefined };
}
export const QueryParamsResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.params !== undefined) {
            Params.encode(message.params, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryParamsResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.params = Params.decode(reader, reader.uint32());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return { params: isSet(object.params) ? Params.fromJSON(object.params) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.params !== undefined) {
            obj.params = Params.toJSON(message.params);
        }
        return obj;
    },
    create(base) {
        return QueryParamsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryParamsResponse();
        message.params = (object.params !== undefined && object.params !== null)
            ? Params.fromPartial(object.params)
            : undefined;
        return message;
    },
};
function createBaseQueryValidatorReserveRequest() {
    return {};
}
export const QueryValidatorReserveRequest = {
    encode(_, writer = new BinaryWriter()) {
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryValidatorReserveRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(_) {
        return {};
    },
    toJSON(_) {
        const obj = {};
        return obj;
    },
    create(base) {
        return QueryValidatorReserveRequest.fromPartial(base ?? {});
    },
    fromPartial(_) {
        const message = createBaseQueryValidatorReserveRequest();
        return message;
    },
};
function createBaseQueryValidatorReserveResponse() {
    return { reserve: undefined, nextRelease: "" };
}
export const QueryValidatorReserveResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.reserve !== undefined) {
            ValidatorReserve.encode(message.reserve, writer.uint32(10).fork()).join();
        }
        if (message.nextRelease !== "") {
            writer.uint32(18).string(message.nextRelease);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryValidatorReserveResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.reserve = ValidatorReserve.decode(reader, reader.uint32());
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.nextRelease = reader.string();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            reserve: isSet(object.reserve) ? ValidatorReserve.fromJSON(object.reserve) : undefined,
            nextRelease: isSet(object.nextRelease)
                ? globalThis.String(object.nextRelease)
                : isSet(object.next_release)
                    ? globalThis.String(object.next_release)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.reserve !== undefined) {
            obj.reserve = ValidatorReserve.toJSON(message.reserve);
        }
        if (message.nextRelease !== "") {
            obj.nextRelease = message.nextRelease;
        }
        return obj;
    },
    create(base) {
        return QueryValidatorReserveResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryValidatorReserveResponse();
        message.reserve = (object.reserve !== undefined && object.reserve !== null)
            ? ValidatorReserve.fromPartial(object.reserve)
            : undefined;
        message.nextRelease = object.nextRelease ?? "";
        return message;
    },
};
function createBaseQueryRestrictedAccountRequest() {
    return { address: "" };
}
export const QueryRestrictedAccountRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.address !== "") {
            writer.uint32(10).string(message.address);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryRestrictedAccountRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.address = reader.string();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return { address: isSet(object.address) ? globalThis.String(object.address) : "" };
    },
    toJSON(message) {
        const obj = {};
        if (message.address !== "") {
            obj.address = message.address;
        }
        return obj;
    },
    create(base) {
        return QueryRestrictedAccountRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryRestrictedAccountRequest();
        message.address = object.address ?? "";
        return message;
    },
};
function createBaseQueryRestrictedAccountResponse() {
    return { account: undefined, available: "" };
}
export const QueryRestrictedAccountResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.account !== undefined) {
            RestrictedAccount.encode(message.account, writer.uint32(10).fork()).join();
        }
        if (message.available !== "") {
            writer.uint32(18).string(message.available);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryRestrictedAccountResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.account = RestrictedAccount.decode(reader, reader.uint32());
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.available = reader.string();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            account: isSet(object.account) ? RestrictedAccount.fromJSON(object.account) : undefined,
            available: isSet(object.available) ? globalThis.String(object.available) : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.account !== undefined) {
            obj.account = RestrictedAccount.toJSON(message.account);
        }
        if (message.available !== "") {
            obj.available = message.available;
        }
        return obj;
    },
    create(base) {
        return QueryRestrictedAccountResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryRestrictedAccountResponse();
        message.account = (object.account !== undefined && object.account !== null)
            ? RestrictedAccount.fromPartial(object.account)
            : undefined;
        message.available = object.available ?? "";
        return message;
    },
};
function createBaseQueryRestrictedAccountsRequest() {
    return { pagination: undefined };
}
export const QueryRestrictedAccountsRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.pagination !== undefined) {
            PageRequest.encode(message.pagination, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryRestrictedAccountsRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.pagination = PageRequest.decode(reader, reader.uint32());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return { pagination: isSet(object.pagination) ? PageRequest.fromJSON(object.pagination) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.pagination !== undefined) {
            obj.pagination = PageRequest.toJSON(message.pagination);
        }
        return obj;
    },
    create(base) {
        return QueryRestrictedAccountsRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryRestrictedAccountsRequest();
        message.pagination = (object.pagination !== undefined && object.pagination !== null)
            ? PageRequest.fromPartial(object.pagination)
            : undefined;
        return message;
    },
};
function createBaseQueryRestrictedAccountsResponse() {
    return { accounts: [], pagination: undefined };
}
export const QueryRestrictedAccountsResponse = {
    encode(message, writer = new BinaryWriter()) {
        for (const v of message.accounts) {
            RestrictedAccount.encode(v, writer.uint32(10).fork()).join();
        }
        if (message.pagination !== undefined) {
            PageResponse.encode(message.pagination, writer.uint32(18).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryRestrictedAccountsResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.accounts.push(RestrictedAccount.decode(reader, reader.uint32()));
                        continue;
                    }
                    case 2: {
                        if (tag !== 18) {
                            break;
                        }
                        message.pagination = PageResponse.decode(reader, reader.uint32());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            accounts: globalThis.Array.isArray(object?.accounts)
                ? object.accounts.map((e) => RestrictedAccount.fromJSON(e))
                : [],
            pagination: isSet(object.pagination) ? PageResponse.fromJSON(object.pagination) : undefined,
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.accounts?.length) {
            obj.accounts = message.accounts.map((e) => RestrictedAccount.toJSON(e));
        }
        if (message.pagination !== undefined) {
            obj.pagination = PageResponse.toJSON(message.pagination);
        }
        return obj;
    },
    create(base) {
        return QueryRestrictedAccountsResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryRestrictedAccountsResponse();
        message.accounts = object.accounts?.map((e) => RestrictedAccount.fromPartial(e)) || [];
        message.pagination = (object.pagination !== undefined && object.pagination !== null)
            ? PageResponse.fromPartial(object.pagination)
            : undefined;
        return message;
    },
};
function createBaseQueryValidatorPerformanceRequest() {
    return { validatorAddress: "" };
}
export const QueryValidatorPerformanceRequest = {
    encode(message, writer = new BinaryWriter()) {
        if (message.validatorAddress !== "") {
            writer.uint32(10).string(message.validatorAddress);
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryValidatorPerformanceRequest();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.validatorAddress = reader.string();
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return {
            validatorAddress: isSet(object.validatorAddress)
                ? globalThis.String(object.validatorAddress)
                : isSet(object.validator_address)
                    ? globalThis.String(object.validator_address)
                    : "",
        };
    },
    toJSON(message) {
        const obj = {};
        if (message.validatorAddress !== "") {
            obj.validatorAddress = message.validatorAddress;
        }
        return obj;
    },
    create(base) {
        return QueryValidatorPerformanceRequest.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryValidatorPerformanceRequest();
        message.validatorAddress = object.validatorAddress ?? "";
        return message;
    },
};
function createBaseQueryValidatorPerformanceResponse() {
    return { performance: undefined };
}
export const QueryValidatorPerformanceResponse = {
    encode(message, writer = new BinaryWriter()) {
        if (message.performance !== undefined) {
            ValidatorPerformance.encode(message.performance, writer.uint32(10).fork()).join();
        }
        return writer;
    },
    decode(input, length) {
        const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
        const previousRecursionDepth = reader.__tsProtoDecodeDepth ?? 0;
        if (previousRecursionDepth >= 100) {
            throw new globalThis.Error("protobuf decode recursion limit exceeded");
        }
        reader.__tsProtoDecodeDepth = previousRecursionDepth + 1;
        try {
            const end = length === undefined ? reader.len : reader.pos + length;
            const message = createBaseQueryValidatorPerformanceResponse();
            while (reader.pos < end) {
                const tag = reader.uint32();
                switch (tag >>> 3) {
                    case 1: {
                        if (tag !== 10) {
                            break;
                        }
                        message.performance = ValidatorPerformance.decode(reader, reader.uint32());
                        continue;
                    }
                }
                if ((tag & 7) === 4 || tag === 0) {
                    break;
                }
                reader.skip(tag & 7);
            }
            return message;
        }
        finally {
            reader.__tsProtoDecodeDepth = previousRecursionDepth;
        }
    },
    fromJSON(object) {
        return { performance: isSet(object.performance) ? ValidatorPerformance.fromJSON(object.performance) : undefined };
    },
    toJSON(message) {
        const obj = {};
        if (message.performance !== undefined) {
            obj.performance = ValidatorPerformance.toJSON(message.performance);
        }
        return obj;
    },
    create(base) {
        return QueryValidatorPerformanceResponse.fromPartial(base ?? {});
    },
    fromPartial(object) {
        const message = createBaseQueryValidatorPerformanceResponse();
        message.performance = (object.performance !== undefined && object.performance !== null)
            ? ValidatorPerformance.fromPartial(object.performance)
            : undefined;
        return message;
    },
};
export const QueryServiceName = "ferac.ferac.v1.Query";
export class QueryClientImpl {
    constructor(rpc, opts) {
        this.service = opts?.service || QueryServiceName;
        this.rpc = rpc;
        this.Params = this.Params.bind(this);
        this.ValidatorReserve = this.ValidatorReserve.bind(this);
        this.RestrictedAccount = this.RestrictedAccount.bind(this);
        this.RestrictedAccounts = this.RestrictedAccounts.bind(this);
        this.ValidatorPerformance = this.ValidatorPerformance.bind(this);
    }
    Params(request) {
        const data = QueryParamsRequest.encode(request).finish();
        const promise = this.rpc.request(this.service, "Params", data);
        return promise.then((data) => QueryParamsResponse.decode(new BinaryReader(data)));
    }
    ValidatorReserve(request) {
        const data = QueryValidatorReserveRequest.encode(request).finish();
        const promise = this.rpc.request(this.service, "ValidatorReserve", data);
        return promise.then((data) => QueryValidatorReserveResponse.decode(new BinaryReader(data)));
    }
    RestrictedAccount(request) {
        const data = QueryRestrictedAccountRequest.encode(request).finish();
        const promise = this.rpc.request(this.service, "RestrictedAccount", data);
        return promise.then((data) => QueryRestrictedAccountResponse.decode(new BinaryReader(data)));
    }
    RestrictedAccounts(request) {
        const data = QueryRestrictedAccountsRequest.encode(request).finish();
        const promise = this.rpc.request(this.service, "RestrictedAccounts", data);
        return promise.then((data) => QueryRestrictedAccountsResponse.decode(new BinaryReader(data)));
    }
    ValidatorPerformance(request) {
        const data = QueryValidatorPerformanceRequest.encode(request).finish();
        const promise = this.rpc.request(this.service, "ValidatorPerformance", data);
        return promise.then((data) => QueryValidatorPerformanceResponse.decode(new BinaryReader(data)));
    }
}
function isSet(value) {
    return value !== null && value !== undefined;
}
