// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               unknown
// source: ferac/ferac/v1/tx.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Params } from "./params";

export const protobufPackage = "ferac.ferac.v1";

/** MsgUpdateParams is the Msg/UpdateParams request type. */
export interface MsgUpdateParams {
  /** authority is the address that controls the module (defaults to x/gov unless overwritten). */
  authority: string;
  /**
   * params defines the module parameters to update.
   *
   * NOTE: All parameters must be supplied.
   */
  params: Params | undefined;
}

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 */
export interface MsgUpdateParamsResponse {
}

/** MsgAnnounceValidatorExit is the Msg/AnnounceValidatorExit request type. */
export interface MsgAnnounceValidatorExit {
  /** sender must be the account address of the validator operator. */
  sender: string;
  /** validator_address is the operator address of the exiting validator. */
  validatorAddress: string;
}

/** MsgAnnounceValidatorExitResponse defines the response structure. */
export interface MsgAnnounceValidatorExitResponse {
  /** allowed_at is the unix time from which self-undelegation is permitted. */
  allowedAt: number;
}

/** MsgSetValidatorQuality is the Msg/SetValidatorQuality request type. */
export interface MsgSetValidatorQuality {
  authority: string;
  validatorAddress: string;
  /** quality_score must be in [0,1]. */
  qualityScore: string;
}

/** MsgSetValidatorQualityResponse defines the response structure. */
export interface MsgSetValidatorQualityResponse {
}

function createBaseMsgUpdateParams(): MsgUpdateParams {
  return { authority: "", params: undefined };
}

export const MsgUpdateParams: MessageFns<MsgUpdateParams> = {
  encode(message: MsgUpdateParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.params !== undefined) {
      Params.encode(message.params, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParams();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.authority = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.params = Params.decode(reader, reader.uint32());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgUpdateParams {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      params: isSet(object.params) ? Params.fromJSON(object.params) : undefined,
    };
  },

  toJSON(message: MsgUpdateParams): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.params !== undefined) {
      obj.params = Params.toJSON(message.params);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(base?: I): MsgUpdateParams {
    return MsgUpdateParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParams>, I>>(object: I): MsgUpdateParams {
    const message = createBaseMsgUpdateParams();
    message.authority = object.authority ?? "";
    message.params = (object.params !== undefined && object.params !== null)
      ? Params.fromPartial(object.params)
      : undefined;
    return message;
  },
};

function createBaseMsgUpdateParamsResponse(): MsgUpdateParamsResponse {
  return {};
}

export const MsgUpdateParamsResponse: MessageFns<MsgUpdateParamsResponse> = {
  encode(_: MsgUpdateParamsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgUpdateParamsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgUpdateParamsResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgUpdateParamsResponse {
    return {};
  },

  toJSON(_: MsgUpdateParamsResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(base?: I): MsgUpdateParamsResponse {
    return MsgUpdateParamsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgUpdateParamsResponse>, I>>(_: I): MsgUpdateParamsResponse {
    const message = createBaseMsgUpdateParamsResponse();
    return message;
  },
};

function createBaseMsgAnnounceValidatorExit(): MsgAnnounceValidatorExit {
  return { sender: "", validatorAddress: "" };
}

export const MsgAnnounceValidatorExit: MessageFns<MsgAnnounceValidatorExit> = {
  encode(message: MsgAnnounceValidatorExit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sender !== "") {
      writer.uint32(10).string(message.sender);
    }
    if (message.validatorAddress !== "") {
      writer.uint32(18).string(message.validatorAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAnnounceValidatorExit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgAnnounceValidatorExit();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.sender = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.validatorAddress = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgAnnounceValidatorExit {
    return {
      sender: isSet(object.sender) ? globalThis.String(object.sender) : "",
      validatorAddress: isSet(object.validatorAddress)
        ? globalThis.String(object.validatorAddress)
        : isSet(object.validator_address)
        ? globalThis.String(object.validator_address)
        : "",
    };
  },

  toJSON(message: MsgAnnounceValidatorExit): unknown {
    const obj: any = {};
    if (message.sender !== "") {
      obj.sender = message.sender;
    }
    if (message.validatorAddress !== "") {
      obj.validatorAddress = message.validatorAddress;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAnnounceValidatorExit>, I>>(base?: I): MsgAnnounceValidatorExit {
    return MsgAnnounceValidatorExit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAnnounceValidatorExit>, I>>(object: I): MsgAnnounceValidatorExit {
    const message = createBaseMsgAnnounceValidatorExit();
    message.sender = object.sender ?? "";
    message.validatorAddress = object.validatorAddress ?? "";
    return message;
  },
};

function createBaseMsgAnnounceValidatorExitResponse(): MsgAnnounceValidatorExitResponse {
  return { allowedAt: 0 };
}

export const MsgAnnounceValidatorExitResponse: MessageFns<MsgAnnounceValidatorExitResponse> = {
  encode(message: MsgAnnounceValidatorExitResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.allowedAt !== 0) {
      writer.uint32(8).int64(message.allowedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgAnnounceValidatorExitResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgAnnounceValidatorExitResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 8) {
              break;
            }

            message.allowedAt = longToNumber(reader.int64());
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgAnnounceValidatorExitResponse {
    return {
      allowedAt: isSet(object.allowedAt)
        ? globalThis.Number(object.allowedAt)
        : isSet(object.allowed_at)
        ? globalThis.Number(object.allowed_at)
        : 0,
    };
  },

  toJSON(message: MsgAnnounceValidatorExitResponse): unknown {
    const obj: any = {};
    if (message.allowedAt !== 0) {
      obj.allowedAt = Math.round(message.allowedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAnnounceValidatorExitResponse>, I>>(
    base?: I,
  ): MsgAnnounceValidatorExitResponse {
    return MsgAnnounceValidatorExitResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAnnounceValidatorExitResponse>, I>>(
    object: I,
  ): MsgAnnounceValidatorExitResponse {
    const message = createBaseMsgAnnounceValidatorExitResponse();
    message.allowedAt = object.allowedAt ?? 0;
    return message;
  },
};

function createBaseMsgSetValidatorQuality(): MsgSetValidatorQuality {
  return { authority: "", validatorAddress: "", qualityScore: "" };
}

export const MsgSetValidatorQuality: MessageFns<MsgSetValidatorQuality> = {
  encode(message: MsgSetValidatorQuality, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.authority !== "") {
      writer.uint32(10).string(message.authority);
    }
    if (message.validatorAddress !== "") {
      writer.uint32(18).string(message.validatorAddress);
    }
    if (message.qualityScore !== "") {
      writer.uint32(26).string(message.qualityScore);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetValidatorQuality {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSetValidatorQuality();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
          case 1: {
            if (tag !== 10) {
              break;
            }

            message.authority = reader.string();
            continue;
          }
          case 2: {
            if (tag !== 18) {
              break;
            }

            message.validatorAddress = reader.string();
            continue;
          }
          case 3: {
            if (tag !== 26) {
              break;
            }

            message.qualityScore = reader.string();
            continue;
          }
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(object: any): MsgSetValidatorQuality {
    return {
      authority: isSet(object.authority) ? globalThis.String(object.authority) : "",
      validatorAddress: isSet(object.validatorAddress)
        ? globalThis.String(object.validatorAddress)
        : isSet(object.validator_address)
        ? globalThis.String(object.validator_address)
        : "",
      qualityScore: isSet(object.qualityScore)
        ? globalThis.String(object.qualityScore)
        : isSet(object.quality_score)
        ? globalThis.String(object.quality_score)
        : "",
    };
  },

  toJSON(message: MsgSetValidatorQuality): unknown {
    const obj: any = {};
    if (message.authority !== "") {
      obj.authority = message.authority;
    }
    if (message.validatorAddress !== "") {
      obj.validatorAddress = message.validatorAddress;
    }
    if (message.qualityScore !== "") {
      obj.qualityScore = message.qualityScore;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetValidatorQuality>, I>>(base?: I): MsgSetValidatorQuality {
    return MsgSetValidatorQuality.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetValidatorQuality>, I>>(object: I): MsgSetValidatorQuality {
    const message = createBaseMsgSetValidatorQuality();
    message.authority = object.authority ?? "";
    message.validatorAddress = object.validatorAddress ?? "";
    message.qualityScore = object.qualityScore ?? "";
    return message;
  },
};

function createBaseMsgSetValidatorQualityResponse(): MsgSetValidatorQualityResponse {
  return {};
}

export const MsgSetValidatorQualityResponse: MessageFns<MsgSetValidatorQualityResponse> = {
  encode(_: MsgSetValidatorQualityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MsgSetValidatorQualityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const previousRecursionDepth = (reader as any).__tsProtoDecodeDepth ?? 0;
    if (previousRecursionDepth >= 100) {
      throw new globalThis.Error("protobuf decode recursion limit exceeded");
    }
    (reader as any).__tsProtoDecodeDepth = previousRecursionDepth + 1;
    try {
      const end = length === undefined ? reader.len : reader.pos + length;
      const message = createBaseMsgSetValidatorQualityResponse();
      while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
        }
        if ((tag & 7) === 4 || tag === 0) {
          break;
        }
        reader.skip(tag & 7);
      }
      return message;
    } finally {
      (reader as any).__tsProtoDecodeDepth = previousRecursionDepth;
    }
  },

  fromJSON(_: any): MsgSetValidatorQualityResponse {
    return {};
  },

  toJSON(_: MsgSetValidatorQualityResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetValidatorQualityResponse>, I>>(base?: I): MsgSetValidatorQualityResponse {
    return MsgSetValidatorQualityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetValidatorQualityResponse>, I>>(_: I): MsgSetValidatorQualityResponse {
    const message = createBaseMsgSetValidatorQualityResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  /**
   * UpdateParams defines a (governance) operation for updating the module
   * parameters. The authority defaults to the x/gov module account.
   */
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse>;
  /**
   * AnnounceValidatorExit starts the validator exit notice period. A validator
   * cannot reduce its self-delegation before the notice period has elapsed.
   */
  AnnounceValidatorExit(request: MsgAnnounceValidatorExit): Promise<MsgAnnounceValidatorExitResponse>;
  /**
   * SetValidatorQuality sets the governance-controlled quality score used by
   * the 40/40/20 validator reward formula.
   */
  SetValidatorQuality(request: MsgSetValidatorQuality): Promise<MsgSetValidatorQualityResponse>;
}

export const MsgServiceName = "ferac.ferac.v1.Msg";
export class MsgClientImpl implements Msg {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || MsgServiceName;
    this.rpc = rpc;
    this.UpdateParams = this.UpdateParams.bind(this);
    this.AnnounceValidatorExit = this.AnnounceValidatorExit.bind(this);
    this.SetValidatorQuality = this.SetValidatorQuality.bind(this);
  }
  UpdateParams(request: MsgUpdateParams): Promise<MsgUpdateParamsResponse> {
    const data = MsgUpdateParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "UpdateParams", data);
    return promise.then((data) => MsgUpdateParamsResponse.decode(new BinaryReader(data)));
  }

  AnnounceValidatorExit(request: MsgAnnounceValidatorExit): Promise<MsgAnnounceValidatorExitResponse> {
    const data = MsgAnnounceValidatorExit.encode(request).finish();
    const promise = this.rpc.request(this.service, "AnnounceValidatorExit", data);
    return promise.then((data) => MsgAnnounceValidatorExitResponse.decode(new BinaryReader(data)));
  }

  SetValidatorQuality(request: MsgSetValidatorQuality): Promise<MsgSetValidatorQualityResponse> {
    const data = MsgSetValidatorQuality.encode(request).finish();
    const promise = this.rpc.request(this.service, "SetValidatorQuality", data);
    return promise.then((data) => MsgSetValidatorQualityResponse.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
